### ISSUE TITLE
AppImage does not run

### ISSUE THREAD

**Issue by probonopd** [jojobyte/githoard#1]
AppImage does not run:
![](https://raw.githubusercontent.com/AppImage/appimage.github.io/bd5d65fcbe04d9e7c563b2a3aaed41da687df564/database/githoard/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/commit/bd5d65fcbe04d9e7c563b2a3aaed41da687df564

**Comment by jojobyte** [comment]
Haven't tested on linux recently. Which version/distro are you on?

**Comment by probonopd** [comment]
Ubuntu 14.04 64-bit.

**Comment by probonopd** [comment]
Thank you, works now.
